# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UkeyTestTool(object):
    def setupUi(self, UkeyTestTool):
        UkeyTestTool.setObjectName("UkeyTestTool")
        UkeyTestTool.resize(1136, 896)
        self.centralwidget = QtWidgets.QWidget(UkeyTestTool)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 1111, 881))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 50, 1081, 431))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 20, 1061, 341))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton1 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton1.setObjectName("pushButton1")
        self.gridLayout_2.addWidget(self.pushButton1, 0, 0, 1, 1)
        self.pushButton11 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton11.setObjectName("pushButton11")
        self.gridLayout_2.addWidget(self.pushButton11, 0, 1, 1, 1)
        self.pushButton21 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton21.setObjectName("pushButton21")
        self.gridLayout_2.addWidget(self.pushButton21, 0, 2, 1, 1)
        self.pushButton31 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton31.setObjectName("pushButton31")
        self.gridLayout_2.addWidget(self.pushButton31, 0, 3, 1, 1)
        self.pushButton41 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton41.setObjectName("pushButton41")
        self.gridLayout_2.addWidget(self.pushButton41, 0, 4, 1, 1)
        self.pushButton51 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton51.setObjectName("pushButton51")
        self.gridLayout_2.addWidget(self.pushButton51, 0, 5, 1, 1)
        self.pushButton61 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton61.setObjectName("pushButton61")
        self.gridLayout_2.addWidget(self.pushButton61, 0, 6, 1, 1)
        self.pushButton71 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton71.setObjectName("pushButton71")
        self.gridLayout_2.addWidget(self.pushButton71, 0, 7, 1, 1)
        self.pushButton81 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton81.setObjectName("pushButton81")
        self.gridLayout_2.addWidget(self.pushButton81, 0, 8, 1, 1)
        self.pushButton2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton2.setObjectName("pushButton2")
        self.gridLayout_2.addWidget(self.pushButton2, 1, 0, 1, 1)
        self.pushButton12 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton12.setObjectName("pushButton12")
        self.gridLayout_2.addWidget(self.pushButton12, 1, 1, 1, 1)
        self.pushButton22 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton22.setObjectName("pushButton22")
        self.gridLayout_2.addWidget(self.pushButton22, 1, 2, 1, 1)
        self.pushButton32 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton32.setObjectName("pushButton32")
        self.gridLayout_2.addWidget(self.pushButton32, 1, 3, 1, 1)
        self.pushButton42 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton42.setObjectName("pushButton42")
        self.gridLayout_2.addWidget(self.pushButton42, 1, 4, 1, 1)
        self.pushButton52 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton52.setObjectName("pushButton52")
        self.gridLayout_2.addWidget(self.pushButton52, 1, 5, 1, 1)
        self.pushButton62 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton62.setObjectName("pushButton62")
        self.gridLayout_2.addWidget(self.pushButton62, 1, 6, 1, 1)
        self.pushButton72 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton72.setObjectName("pushButton72")
        self.gridLayout_2.addWidget(self.pushButton72, 1, 7, 1, 1)
        self.pushButton82 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton82.setObjectName("pushButton82")
        self.gridLayout_2.addWidget(self.pushButton82, 1, 8, 1, 1)
        self.pushButton3 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton3.setObjectName("pushButton3")
        self.gridLayout_2.addWidget(self.pushButton3, 2, 0, 1, 1)
        self.pushButton13 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton13.setObjectName("pushButton13")
        self.gridLayout_2.addWidget(self.pushButton13, 2, 1, 1, 1)
        self.pushButton23 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton23.setObjectName("pushButton23")
        self.gridLayout_2.addWidget(self.pushButton23, 2, 2, 1, 1)
        self.pushButton33 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton33.setObjectName("pushButton33")
        self.gridLayout_2.addWidget(self.pushButton33, 2, 3, 1, 1)
        self.pushButton43 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton43.setObjectName("pushButton43")
        self.gridLayout_2.addWidget(self.pushButton43, 2, 4, 1, 1)
        self.pushButton53 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton53.setObjectName("pushButton53")
        self.gridLayout_2.addWidget(self.pushButton53, 2, 5, 1, 1)
        self.pushButton63 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton63.setObjectName("pushButton63")
        self.gridLayout_2.addWidget(self.pushButton63, 2, 6, 1, 1)
        self.pushButton73 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton73.setObjectName("pushButton73")
        self.gridLayout_2.addWidget(self.pushButton73, 2, 7, 1, 1)
        self.pushButton83 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton83.setObjectName("pushButton83")
        self.gridLayout_2.addWidget(self.pushButton83, 2, 8, 1, 1)
        self.pushButton4 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton4.setObjectName("pushButton4")
        self.gridLayout_2.addWidget(self.pushButton4, 3, 0, 1, 1)
        self.pushButton14 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton14.setObjectName("pushButton14")
        self.gridLayout_2.addWidget(self.pushButton14, 3, 1, 1, 1)
        self.pushButton24 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton24.setObjectName("pushButton24")
        self.gridLayout_2.addWidget(self.pushButton24, 3, 2, 1, 1)
        self.pushButton34 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton34.setObjectName("pushButton34")
        self.gridLayout_2.addWidget(self.pushButton34, 3, 3, 1, 1)
        self.pushButton44 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton44.setObjectName("pushButton44")
        self.gridLayout_2.addWidget(self.pushButton44, 3, 4, 1, 1)
        self.pushButton54 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton54.setObjectName("pushButton54")
        self.gridLayout_2.addWidget(self.pushButton54, 3, 5, 1, 1)
        self.pushButton64 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton64.setObjectName("pushButton64")
        self.gridLayout_2.addWidget(self.pushButton64, 3, 6, 1, 1)
        self.pushButton74 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton74.setObjectName("pushButton74")
        self.gridLayout_2.addWidget(self.pushButton74, 3, 7, 1, 1)
        self.pushButton84 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton84.setObjectName("pushButton84")
        self.gridLayout_2.addWidget(self.pushButton84, 3, 8, 1, 1)
        self.pushButton5 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton5.setObjectName("pushButton5")
        self.gridLayout_2.addWidget(self.pushButton5, 4, 0, 1, 1)
        self.pushButton15 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton15.setObjectName("pushButton15")
        self.gridLayout_2.addWidget(self.pushButton15, 4, 1, 1, 1)
        self.pushButton25 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton25.setObjectName("pushButton25")
        self.gridLayout_2.addWidget(self.pushButton25, 4, 2, 1, 1)
        self.pushButton35 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton35.setObjectName("pushButton35")
        self.gridLayout_2.addWidget(self.pushButton35, 4, 3, 1, 1)
        self.pushButton45 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton45.setObjectName("pushButton45")
        self.gridLayout_2.addWidget(self.pushButton45, 4, 4, 1, 1)
        self.pushButton55 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton55.setObjectName("pushButton55")
        self.gridLayout_2.addWidget(self.pushButton55, 4, 5, 1, 1)
        self.pushButton65 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton65.setObjectName("pushButton65")
        self.gridLayout_2.addWidget(self.pushButton65, 4, 6, 1, 1)
        self.pushButton75 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton75.setObjectName("pushButton75")
        self.gridLayout_2.addWidget(self.pushButton75, 4, 7, 1, 1)
        self.pushButton85 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton85.setObjectName("pushButton85")
        self.gridLayout_2.addWidget(self.pushButton85, 4, 8, 1, 1)
        self.pushButton6 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton6.setObjectName("pushButton6")
        self.gridLayout_2.addWidget(self.pushButton6, 5, 0, 1, 1)
        self.pushButton16 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton16.setObjectName("pushButton16")
        self.gridLayout_2.addWidget(self.pushButton16, 5, 1, 1, 1)
        self.pushButton26 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton26.setObjectName("pushButton26")
        self.gridLayout_2.addWidget(self.pushButton26, 5, 2, 1, 1)
        self.pushButton36 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton36.setObjectName("pushButton36")
        self.gridLayout_2.addWidget(self.pushButton36, 5, 3, 1, 1)
        self.pushButton46 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton46.setObjectName("pushButton46")
        self.gridLayout_2.addWidget(self.pushButton46, 5, 4, 1, 1)
        self.pushButton56 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton56.setObjectName("pushButton56")
        self.gridLayout_2.addWidget(self.pushButton56, 5, 5, 1, 1)
        self.pushButton66 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton66.setObjectName("pushButton66")
        self.gridLayout_2.addWidget(self.pushButton66, 5, 6, 1, 1)
        self.pushButton76 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton76.setObjectName("pushButton76")
        self.gridLayout_2.addWidget(self.pushButton76, 5, 7, 1, 1)
        self.pushButton86 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton86.setObjectName("pushButton86")
        self.gridLayout_2.addWidget(self.pushButton86, 5, 8, 1, 1)
        self.pushButton7 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton7.setObjectName("pushButton7")
        self.gridLayout_2.addWidget(self.pushButton7, 6, 0, 1, 1)
        self.pushButton17 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton17.setObjectName("pushButton17")
        self.gridLayout_2.addWidget(self.pushButton17, 6, 1, 1, 1)
        self.pushButton27 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton27.setObjectName("pushButton27")
        self.gridLayout_2.addWidget(self.pushButton27, 6, 2, 1, 1)
        self.pushButton37 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton37.setObjectName("pushButton37")
        self.gridLayout_2.addWidget(self.pushButton37, 6, 3, 1, 1)
        self.pushButton47 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton47.setObjectName("pushButton47")
        self.gridLayout_2.addWidget(self.pushButton47, 6, 4, 1, 1)
        self.pushButton57 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton57.setObjectName("pushButton57")
        self.gridLayout_2.addWidget(self.pushButton57, 6, 5, 1, 1)
        self.pushButton67 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton67.setObjectName("pushButton67")
        self.gridLayout_2.addWidget(self.pushButton67, 6, 6, 1, 1)
        self.pushButton77 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton77.setObjectName("pushButton77")
        self.gridLayout_2.addWidget(self.pushButton77, 6, 7, 1, 1)
        self.pushButton87 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton87.setObjectName("pushButton87")
        self.gridLayout_2.addWidget(self.pushButton87, 6, 8, 1, 1)
        self.pushButton8 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton8.setObjectName("pushButton8")
        self.gridLayout_2.addWidget(self.pushButton8, 7, 0, 1, 1)
        self.pushButton18 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton18.setObjectName("pushButton18")
        self.gridLayout_2.addWidget(self.pushButton18, 7, 1, 1, 1)
        self.pushButton28 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton28.setObjectName("pushButton28")
        self.gridLayout_2.addWidget(self.pushButton28, 7, 2, 1, 1)
        self.pushButton38 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton38.setObjectName("pushButton38")
        self.gridLayout_2.addWidget(self.pushButton38, 7, 3, 1, 1)
        self.pushButton48 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton48.setObjectName("pushButton48")
        self.gridLayout_2.addWidget(self.pushButton48, 7, 4, 1, 1)
        self.pushButton58 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton58.setObjectName("pushButton58")
        self.gridLayout_2.addWidget(self.pushButton58, 7, 5, 1, 1)
        self.pushButton68 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton68.setObjectName("pushButton68")
        self.gridLayout_2.addWidget(self.pushButton68, 7, 6, 1, 1)
        self.pushButton78 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton78.setObjectName("pushButton78")
        self.gridLayout_2.addWidget(self.pushButton78, 7, 7, 1, 1)
        self.pushButton88 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton88.setObjectName("pushButton88")
        self.gridLayout_2.addWidget(self.pushButton88, 7, 8, 1, 1)
        self.pushButton9 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton9.setObjectName("pushButton9")
        self.gridLayout_2.addWidget(self.pushButton9, 8, 0, 1, 1)
        self.pushButton19 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton19.setObjectName("pushButton19")
        self.gridLayout_2.addWidget(self.pushButton19, 8, 1, 1, 1)
        self.pushButton29 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton29.setObjectName("pushButton29")
        self.gridLayout_2.addWidget(self.pushButton29, 8, 2, 1, 1)
        self.pushButton39 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton39.setObjectName("pushButton39")
        self.gridLayout_2.addWidget(self.pushButton39, 8, 3, 1, 1)
        self.pushButton49 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton49.setObjectName("pushButton49")
        self.gridLayout_2.addWidget(self.pushButton49, 8, 4, 1, 1)
        self.pushButton59 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton59.setObjectName("pushButton59")
        self.gridLayout_2.addWidget(self.pushButton59, 8, 5, 1, 1)
        self.pushButton69 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton69.setObjectName("pushButton69")
        self.gridLayout_2.addWidget(self.pushButton69, 8, 6, 1, 1)
        self.pushButton79 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton79.setObjectName("pushButton79")
        self.gridLayout_2.addWidget(self.pushButton79, 8, 7, 1, 1)
        self.pushButton89 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton89.setObjectName("pushButton89")
        self.gridLayout_2.addWidget(self.pushButton89, 8, 8, 1, 1)
        self.pushButton10 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton10.setObjectName("pushButton10")
        self.gridLayout_2.addWidget(self.pushButton10, 9, 0, 1, 1)
        self.pushButton20 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton20.setObjectName("pushButton20")
        self.gridLayout_2.addWidget(self.pushButton20, 9, 1, 1, 1)
        self.pushButton30 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton30.setObjectName("pushButton30")
        self.gridLayout_2.addWidget(self.pushButton30, 9, 2, 1, 1)
        self.pushButton40 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton40.setObjectName("pushButton40")
        self.gridLayout_2.addWidget(self.pushButton40, 9, 3, 1, 1)
        self.pushButton50 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton50.setObjectName("pushButton50")
        self.gridLayout_2.addWidget(self.pushButton50, 9, 4, 1, 1)
        self.pushButton60 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton60.setObjectName("pushButton60")
        self.gridLayout_2.addWidget(self.pushButton60, 9, 5, 1, 1)
        self.pushButton70 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton70.setObjectName("pushButton70")
        self.gridLayout_2.addWidget(self.pushButton70, 9, 6, 1, 1)
        self.pushButton80 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton80.setObjectName("pushButton80")
        self.gridLayout_2.addWidget(self.pushButton80, 9, 7, 1, 1)
        self.pushButton_89 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pushButton_89.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton_89.setObjectName("pushButton_89")
        self.gridLayout_2.addWidget(self.pushButton_89, 9, 8, 1, 1)
        self.pushButton43_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton43_2.setGeometry(QtCore.QRect(10, 370, 111, 23))
        self.pushButton43_2.setObjectName("pushButton43_2")
        self.pushButton43_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton43_3.setGeometry(QtCore.QRect(10, 400, 111, 23))
        self.pushButton43_3.setObjectName("pushButton43_3")
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 490, 1081, 101))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 1061, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton91 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton91.setObjectName("pushButton91")
        self.horizontalLayout.addWidget(self.pushButton91)
        self.pushButton92 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton92.setObjectName("pushButton92")
        self.horizontalLayout.addWidget(self.pushButton92)
        self.pushButton93 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton93.setObjectName("pushButton93")
        self.horizontalLayout.addWidget(self.pushButton93)
        self.pushButton94 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton94.setObjectName("pushButton94")
        self.horizontalLayout.addWidget(self.pushButton94)
        self.pushButton95 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton95.setObjectName("pushButton95")
        self.horizontalLayout.addWidget(self.pushButton95)
        self.pushButton96 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton96.setObjectName("pushButton96")
        self.horizontalLayout.addWidget(self.pushButton96)
        self.pushButton97 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton97.setObjectName("pushButton97")
        self.horizontalLayout.addWidget(self.pushButton97)
        self.pushButton98 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton98.setObjectName("pushButton98")
        self.horizontalLayout.addWidget(self.pushButton98)
        self.pushButton99 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton99.setObjectName("pushButton99")
        self.horizontalLayout.addWidget(self.pushButton99)
        self.pushButton100 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton100.setObjectName("pushButton100")
        self.horizontalLayout.addWidget(self.pushButton100)
        self.pushButton1_5 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton1_5.setGeometry(QtCore.QRect(110, 60, 111, 23))
        self.pushButton1_5.setObjectName("pushButton1_5")
        self.pushButton1_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton1_6.setGeometry(QtCore.QRect(230, 60, 111, 23))
        self.pushButton1_6.setObjectName("pushButton1_6")
        self.textBrowser = QtWidgets.QTextEdit(self.groupBox_2)
        self.textBrowser.setGeometry(QtCore.QRect(10, 640, 1081, 231))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 10, 111, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton1_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton1_2.setGeometry(QtCore.QRect(20, 600, 111, 23))
        self.pushButton1_2.setObjectName("pushButton1_2")
        self.pushButton1_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton1_3.setGeometry(QtCore.QRect(750, 600, 111, 23))
        self.pushButton1_3.setObjectName("pushButton1_3")
        self.pushButton1_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton1_4.setGeometry(QtCore.QRect(890, 600, 111, 23))
        self.pushButton1_4.setObjectName("pushButton1_4")
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        # UkeyTestTool.setCentralWidget(self.centralwidget)

        self.retranslateUi(UkeyTestTool)
        QtCore.QMetaObject.connectSlotsByName(UkeyTestTool)

    def retranslateUi(self, UkeyTestTool):
        _translate = QtCore.QCoreApplication.translate
        UkeyTestTool.setWindowTitle(_translate("UkeyTestTool", "UkeyTestTool"))
        self.groupBox_3.setTitle(_translate("UkeyTestTool", "功能测试"))
        self.pushButton1.setText(_translate("UkeyTestTool", "枚举设备"))
        self.pushButton11.setText(_translate("UkeyTestTool", "修改设备密钥"))
        self.pushButton21.setText(_translate("UkeyTestTool", "枚举应用"))
        self.pushButton31.setText(_translate("UkeyTestTool", "创建容器"))
        self.pushButton41.setText(_translate("UkeyTestTool", "生成部分签名密钥"))
        self.pushButton51.setText(_translate("UkeyTestTool", "发方生成协商参数"))
        self.pushButton61.setText(_translate("UkeyTestTool", "单组杂凑"))
        self.pushButton71.setText(_translate("UkeyTestTool", "导出矩阵"))
        self.pushButton81.setText(_translate("UkeyTestTool", "随机数单次检测"))
        self.pushButton2.setText(_translate("UkeyTestTool", "连接设备"))
        self.pushButton12.setText(_translate("UkeyTestTool", "设备认证"))
        self.pushButton22.setText(_translate("UkeyTestTool", "打开应用"))
        self.pushButton32.setText(_translate("UkeyTestTool", "删除容器"))
        self.pushButton42.setText(_translate("UkeyTestTool", "导入加密密钥对"))
        self.pushButton52.setText(_translate("UkeyTestTool", "收方计算会话密钥"))
        self.pushButton62.setText(_translate("UkeyTestTool", "多组杂凑"))
        self.pushButton72.setText(_translate("UkeyTestTool", "删除矩阵"))
        self.pushButton82.setText(_translate("UkeyTestTool", "快速Hash初始化"))
        self.pushButton3.setText(_translate("UkeyTestTool", "断开设备"))
        self.pushButton13.setText(_translate("UkeyTestTool", "校验用户PIN"))
        self.pushButton23.setText(_translate("UkeyTestTool", "关闭应用"))
        self.pushButton33.setText(_translate("UkeyTestTool", "打开容器"))
        self.pushButton43.setText(_translate("UkeyTestTool", "Ecc签名"))
        self.pushButton53.setText(_translate("UkeyTestTool", "发方计算会话密钥"))
        self.pushButton63.setText(_translate("UkeyTestTool", "结束杂凑"))
        self.pushButton73.setText(_translate("UkeyTestTool", "标识计算公钥"))
        self.pushButton83.setText(_translate("UkeyTestTool", "多组快速Hash"))
        self.pushButton4.setText(_translate("UkeyTestTool", "设置设备标签"))
        self.pushButton14.setText(_translate("UkeyTestTool", "修改用户PIN"))
        self.pushButton24.setText(_translate("UkeyTestTool", "删除应用"))
        self.pushButton34.setText(_translate("UkeyTestTool", "关闭容器"))
        self.pushButton44.setText(_translate("UkeyTestTool", "ECC验签"))
        self.pushButton54.setText(_translate("UkeyTestTool", "加密初始化"))
        self.pushButton64.setText(_translate("UkeyTestTool", "MAC初始化"))
        self.pushButton74.setText(_translate("UkeyTestTool", "加域计算公钥"))
        self.pushButton84.setText(_translate("UkeyTestTool", "结束多组快速Hash"))
        self.pushButton5.setText(_translate("UkeyTestTool", "获取设备状态"))
        self.pushButton15.setText(_translate("UkeyTestTool", "校验管理PIN"))
        self.pushButton25.setText(_translate("UkeyTestTool", "创建文件"))
        self.pushButton35.setText(_translate("UkeyTestTool", "枚举容器"))
        self.pushButton45.setText(_translate("UkeyTestTool", "ECC导出会话密钥"))
        self.pushButton55.setText(_translate("UkeyTestTool", "多组数据加密"))
        self.pushButton65.setText(_translate("UkeyTestTool", "单组MAC"))
        self.pushButton75.setText(_translate("UkeyTestTool", "IKI导出会话密钥"))
        self.pushButton85.setText(_translate("UkeyTestTool", "VPN发方生成协商参数"))
        self.pushButton6.setText(_translate("UkeyTestTool", "获取设备信息"))
        self.pushButton16.setText(_translate("UkeyTestTool", "修改管理PIN"))
        self.pushButton26.setText(_translate("UkeyTestTool", "删除文件"))
        self.pushButton36.setText(_translate("UkeyTestTool", "获取容器类型"))
        self.pushButton46.setText(_translate("UkeyTestTool", "导入会话密钥"))
        self.pushButton56.setText(_translate("UkeyTestTool", "结束加密"))
        self.pushButton66.setText(_translate("UkeyTestTool", "多组MAC"))
        self.pushButton76.setText(_translate("UkeyTestTool", "IKI导出服务端密钥"))
        self.pushButton86.setText(_translate("UkeyTestTool", "VPN收方计算会话密钥"))
        self.pushButton7.setText(_translate("UkeyTestTool", "锁定设备"))
        self.pushButton17.setText(_translate("UkeyTestTool", "获取PIN信息"))
        self.pushButton27.setText(_translate("UkeyTestTool", "枚举文件"))
        self.pushButton37.setText(_translate("UkeyTestTool", "导入数字证书"))
        self.pushButton47.setText(_translate("UkeyTestTool", "导出签名公钥"))
        self.pushButton57.setText(_translate("UkeyTestTool", "解密初始化"))
        self.pushButton67.setText(_translate("UkeyTestTool", "结束MAC"))
        self.pushButton77.setText(_translate("UkeyTestTool", "销毁会话密钥"))
        self.pushButton87.setText(_translate("UkeyTestTool", "VPN发方计算会话密钥"))
        self.pushButton8.setText(_translate("UkeyTestTool", "解锁设备"))
        self.pushButton18.setText(_translate("UkeyTestTool", "解锁PIN"))
        self.pushButton28.setText(_translate("UkeyTestTool", "获取文件属性"))
        self.pushButton38.setText(_translate("UkeyTestTool", "导出数字证书"))
        self.pushButton48.setText(_translate("UkeyTestTool", "导出加密公钥"))
        self.pushButton58.setText(_translate("UkeyTestTool", "多组数据解密"))
        self.pushButton68.setText(_translate("UkeyTestTool", "导入实体标识"))
        self.pushButton78.setText(_translate("UkeyTestTool", "导入RPK"))
        self.pushButton88.setText(_translate("UkeyTestTool", "SM2签名"))
        self.pushButton9.setText(_translate("UkeyTestTool", "等待插拔"))
        self.pushButton19.setText(_translate("UkeyTestTool", "清除应用安全状态"))
        self.pushButton29.setText(_translate("UkeyTestTool", "写文件"))
        self.pushButton39.setText(_translate("UkeyTestTool", "生成随机数"))
        self.pushButton49.setText(_translate("UkeyTestTool", "导出保护公钥"))
        self.pushButton59.setText(_translate("UkeyTestTool", "结束解密"))
        self.pushButton69.setText(_translate("UkeyTestTool", "导出实体标识"))
        self.pushButton79.setText(_translate("UkeyTestTool", "导出RPK"))
        self.pushButton89.setText(_translate("UkeyTestTool", "SM2验签"))
        self.pushButton10.setText(_translate("UkeyTestTool", "取消等待插拔"))
        self.pushButton20.setText(_translate("UkeyTestTool", "创建应用"))
        self.pushButton30.setText(_translate("UkeyTestTool", "读取文件"))
        self.pushButton40.setText(_translate("UkeyTestTool", "生成保护密钥对"))
        self.pushButton50.setText(_translate("UkeyTestTool", "ECC外来公钥加密"))
        self.pushButton60.setText(_translate("UkeyTestTool", "杂凑初始化"))
        self.pushButton70.setText(_translate("UkeyTestTool", "导入矩阵"))
        self.pushButton80.setText(_translate("UkeyTestTool", "随机数检测"))
        self.pushButton_89.setText(_translate("UkeyTestTool", "查看运行日志"))
        self.pushButton43_2.setText(_translate("UkeyTestTool", "RSA签名"))
        self.pushButton43_3.setText(_translate("UkeyTestTool", "RSA验签"))
        self.groupBox.setTitle(_translate("UkeyTestTool", "性能测试"))
        self.pushButton91.setText(_translate("UkeyTestTool", "生成密钥对"))
        self.pushButton92.setText(_translate("UkeyTestTool", "SM2签名"))
        self.pushButton93.setText(_translate("UkeyTestTool", "SM2验签"))
        self.pushButton94.setText(_translate("UkeyTestTool", "SM2加密"))
        self.pushButton95.setText(_translate("UkeyTestTool", "SM2解密"))
        self.pushButton96.setText(_translate("UkeyTestTool", "SM3杂凑"))
        self.pushButton97.setText(_translate("UkeyTestTool", "SM4加密"))
        self.pushButton98.setText(_translate("UkeyTestTool", "SM4解密"))
        self.pushButton99.setText(_translate("UkeyTestTool", "写文件"))
        self.pushButton100.setText(_translate("UkeyTestTool", "读文件"))
        self.pushButton1_5.setText(_translate("UkeyTestTool", "SM2签名（无证书）"))
        self.pushButton1_6.setText(_translate("UkeyTestTool", "SM2验签（无证书）"))
        self.textBrowser.setHtml(_translate("UkeyTestTool", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton_2.setText(_translate("UkeyTestTool", "初始化设备"))
        self.pushButton1_2.setText(_translate("UkeyTestTool", "导出公钥矩阵Hash"))
        self.pushButton1_3.setText(_translate("UkeyTestTool", "SM2签名（无证书）"))
        self.pushButton1_4.setText(_translate("UkeyTestTool", "SM2验签（无证书）"))
